# Generated by Django 5.2.12 on 2026-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.0, help_text='Course unlock price in USD', max_digits=10),
        ),
    ]
