# Generated by Django 5.2.12 on 2026-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='EduManage Instructor', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Mixed', 'Mixed')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL of the course cover image', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.TextField(blank=True, help_text='Newline-separated list of learning outcomes', null=True),
        ),
    ]
